-- Criar tabela de movimentações de estoque
CREATE TABLE stock_movements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES products(id),
    movement_type VARCHAR2(10) CHECK (movement_type IN ('IN', 'OUT')),
    quantity NUMBER NOT NULL,
    movement_date DATE DEFAULT SYSDATE
);